version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/run:
          record: true
          parallel: true 
          parallelism: 2 
          group: 'all ag grid tests'